title: "Dheerajnag Nelanutala"

description: "Helping organizations make better decisions under uncertainty."

url: "https://ndnag.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

sass:
  style: compressed

plugins:
  - jekyll-include-cache

author:
  name: "Dheerajnag Nelanutala"
  excerpt: "Helping organizations make better decisions under uncertainty."
