title: "Nelanutala Dheerajnag"
description: "Finance, Strategy and Financial Modeling"
url: "https://ndnag.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Nelanutala Dheerajnag"
  bio: "Transaction Advisory | Financial Modeling | Healthcare Strategy"
